[[ch11]]
== Bitcoin 보안

비트 코인은 은행 계좌의 잔액처럼 비트 동전이 가치에 대한 추상적 인 참조가 아니기 때문에 도전적입니다. Bitcoin은 디지털 현금이나 금과 매우 비슷합니다. 당신은 아마도 "소유권은 법의 9 분의 1입니다."라는 말을 들었을 것입니다. 음, 비트 코인 (bitcoin)에서, 소지는 법의 십분의 일입니다. 비트 코인을 풀기위한 열쇠의 소유는 현금 보유 또는 귀금속 덩어리와 같습니다. 잃어 버리거나, 놓치거나, 도난 당하거나, 실수로 누군가에게 잘못한 금액을 줄 수 있습니다. 이 모든 경우에있어 사용자는 공공 보도에 현금을 내린 것처럼 의지하지 않습니다.

그러나 비트 코인은 현금, 금, 은행 계좌에없는 기능을 가지고 있습니다. 키를 포함하는 비트 코인 지갑은 모든 파일처럼 백업 할 수 있습니다. 하드 카피 백업을 위해 종이에 인쇄 된 경우에도 여러 복사본에 저장할 수 있습니다. 현금, 금 또는 은행 계좌를 "백업"할 수 없습니다. Bitcoin은 우리가 비트 코인 보안을 새로운 방식으로 생각할 필요가있는 것과는 충분히 다릅니다.

=== 보안 원칙

((("security", "security principles", id="Sprinc11")))((("decentralized systems", "security of")))비트 코인의 핵심 원칙은 분권화 (decentralization)이며 보안에 중요한 영향을 미친다는 점을 강조합니다. (( "보안", "보안 원칙", id = "Sprinc11"))) 전통적인 은행이나 지불 네트워크와 같은 중앙 집중식 모델은 악의적 인 행위자를 시스템 밖으로 보호하기 위해 액세스 제어 및 심사에 의존합니다. 이와 반대로 비트 코인과 같은 분산 시스템은 책임과 통제를 사용자에게 강요합니다. 네트워크 보안은 액세스 제어가 아닌 작업 증명을 기반으로하기 때문에 네트워크를 열어서 Bitcoin 트래픽에 대한 암호화가 필요하지 않습니다.

신용 카드 시스템과 같은 기존 결제 네트워크에서는 사용자의 개인 식별자 (신용 카드 번호)가 포함되어 있기 때문에 지불금은 무제한입니다. 최초 청구 후 식별자에 액세스 할 수있는 사람은 자금을 "가져 와서"소유자에게 반복해서 청구 할 수 있습니다. 따라서 지불 네트워크는 암호화로 종단 간 보안을 유지해야하며, 도청 자나 중개자가 전송 중 또는 전송 중 (저장 중)에 침해 할 수 없도록해야합니다. 나쁜 액터가 시스템에 액세스하면 새 트랜잭션을 생성하는 데 사용할 수있는 현재 트랜잭션 및 지불 토큰을 손상시킬 수 있습니다. 더욱이 고객 데이터가 유출되면 고객이 신분 도용에 노출되어 손상된 계정의 사기 사용을 방지하기위한 조치를 취해야합니다.

Bitcoin은 극적으로 다릅니다. 비트 코인 트랜잭션은 특정 수신자에게만 특정 값을 허용하며 위조되거나 수정 될 수 없습니다. 당사자의 신원과 같은 개인 정보는 공개하지 않으며 추가 지불 권한을 부여하는 데 사용할 수 없습니다. 따라서 비트 코인 결제 네트워크는 암호화되거나 도청으로부터 보호받을 필요가 없습니다. 실제로 보안 상 손실이없는 보안되지 않은 WiFi 또는 Bluetooth와 같은 공개 공개 채널을 통해 비트 코 인 트랜잭션을 브로드 캐스트 할 수 있습니다.

Bitcoin의 분산 보안 모델은 사용자의 힘을 십분 발휘합니다. 그 힘으로 열쇠의 기밀을 유지해야 할 책임이 있습니다. 특히 인터넷에 연결된 스마트 폰이나 랩톱과 같은 범용 컴퓨팅 장치에서 쉽게 할 수없는 대부분의 사용자에게 적합합니다. Bitcoin의 분산 모델은 신용 카드로 볼 수있는 대량의 손상을 방지하지만 많은 사용자는 키를 적절히 보호하고 해킹 당할 수 없습니다.

==== Bitcoin 시스템을 안전하게 개발하기

((("decentralized systems", "bitcoin as")))비트 동전 개발자의 가장 중요한 원칙은 분권화입니다. 대부분의 개발자는 중앙 집중식 보안 모델에 익숙하며 이러한 모델을 비트 코인 응용 프로그램에 적용하여 비참한 결과를 얻으 려합니다.

Bitcoin의 보안은 키에 대한 분산 제어와 광부에 의한 독립적 인 트랜잭션 검증에 의존합니다. Bitcoin의 보안을 활용하려면 Bitcoin 보안 모델 내에 있어야합니다. 간단히 말하자면 사용자의 키를 제어하지 말고 블록 체인에서 트랜잭션을 가져 가지 마십시오.

예를 들어, 많은 초기 비트 코인 교환은 단일 서버에 저장된 키를 사용하여 단일 "핫"지갑에 모든 사용자 자금을 집중 시켰습니다. 이러한 설계는 사용자의 제어를 제거하고 단일 시스템의 키에 대한 제어를 중앙 집중화합니다. 많은 시스템이 해킹되어 고객에게 큰 재앙을 초래했습니다.

((("transactions", "off blockchain")))((("off-blockchain transactions")))또 다른 일반적인 실수는 트랜잭션 비용을 줄이거 나 트랜잭션 처리를 가속화하기 위해 트랜잭션을 "블록 체인에서"제거하는 것입니다. "오프 블록 체인 (off blockchain)"시스템은 트랜잭션을 내부의 중앙 집중식 원장에 기록하고 때로는 비트 코인 블록 체인과 동기화합니다. 이 관행은 분산 된 비트 동전 보안을 독점적이고 중앙 집중식 방식으로 대체합니다. 트랜잭션이 블록 체인을 벗어나면 부적절하게 보호 된 중앙 집중식 원장이 위조되어 자금이 전환되고 준비금이 소진 될 수 있습니다.

운영 보안, 여러 계층의 액세스 제어 및 감사 (전통적인 은행처럼)에 집중적으로 투자 할 준비가되어 있지 않다면 Bitcoin의 분산 보안 컨텍스트 외부에서 자금을 사용하기 전에 매우 신중하게 생각해야합니다. 강건한 보안 모델을 구현하기위한 자금과 규율을 갖고 있다고하더라도, 그러한 설계는 신원 도용, 부패 및 횡령으로 어려움을 겪고있는 기존 금융 네트워크의 취약한 모델을 복제하기 만합니다. 비트 코인 고유의 분산 보안 모델을 이용하려면 친숙하지만 궁극적으로 비트 코인의 보안을 파괴 할 수있는 중앙 집중식 아키텍처의 유혹을 피해야합니다.

==== 트러스트의 뿌리

((("root of trust concept")))전통적인 보안 아키텍처는 _root of _라는 개념을 기반으로하며, 전체 시스템이나 응용 프로그램의 보안을위한 기반으로 사용되는 신뢰할 수있는 코어입니다. 보안 아키텍처는 신뢰의 뿌리를 중심으로 양파의 레이어와 같은 일련의 동심원으로 개발되어 중앙에서 신뢰가 확장됩니다. 각 계층은 액세스 제어, 디지털 서명, 암호화 및 기타 보안 기본 요소를 사용하여보다 신뢰할 수있는 내부 계층을 기반으로합니다. 소프트웨어 시스템이 복잡 해짐에 따라 버그가 포함되어 보안 취약성에 취약해질 수 있습니다. 결과적으로 소프트웨어 시스템이 복잡해질수록 보안이 강화됩니다. 신뢰 개념의 루트는 대부분의 신뢰가 시스템의 가장 복잡한 부분에 배치되도록 보장합니다. 따라서 가장 취약한 부분 인 시스템의 일부는 더 복잡한 소프트웨어가 계층화되어 있습니다. 이 보안 아키텍처는 서로 다른 규모로 반복되어 하나의 시스템 하드웨어에서 신뢰의 루트를 설정 한 다음 운영 체제에서 상위 수준의 시스템 서비스로 확장하고 마지막으로 동심원에있는 여러 서버에 걸쳐 확장합니다. 신뢰 감소.

((("mining and consensus", "security and consensus")))Bitcoin 보안 아키텍처는 다릅니다. 비트 코인에서는 합의 시스템이 완전히 분산 된 신뢰할 수있는 공공 원장을 만듭니다. 올바르게 검증 된 블록 체인은 기생 블록을 신뢰의 루트로 사용하여 현재 블록까지의 신뢰 체인을 구축합니다. Bitcoin 시스템은 신뢰의 뿌리로서 블록 체인을 사용할 수 있고 사용해야합니다. 많은 시스템에서 서비스로 구성된 복잡한 비트 코인 애플리케이션을 설계 할 때는 신뢰가 놓이는 위치를 확인하기 위해 보안 아키텍처를주의 깊게 조사해야합니다. 궁극적으로 명시 적으로 신뢰할 수 있어야하는 것은 완전히 검증 된 블록 체인입니다. 응용 프로그램이 명시 적 또는 암시 적으로 블록 체인 이외의 다른 요소에 대한 신뢰도를 명시하는 경우, 그것은 취약점을 야기하기 때문에 걱정의 근원이되어야합니다. 응용 프로그램의 보안 아키텍처를 평가하는 좋은 방법은 각 개별 구성 요소를 고려하여 해당 구성 요소가 완전히 손상되고 악의적 인 행위자가 제어하는 ​​가설 시나리오를 평가하는 것입니다. 응용 프로그램의 각 구성 요소를 차례로 가져 와서 해당 구성 요소가 손상된 경우 전체 보안에 미치는 영향을 평가하십시오. 구성 요소가 손상되었을 때 응용 프로그램이 더 이상 안전하지 않으면 해당 구성 요소에 대한 신뢰가 잘못되었다는 것을 나타냅니다. 취약점이없는 비트 코인 응용 프로그램은 비트 코인 합의 메커니즘의 손상에 취약해야합니다. 즉, 루트의 신뢰는 비트 코닉 보안 아키텍처의 가장 강력한 부분을 기반으로합니다. 응용 프로그램의 보안 아키텍처를 평가하는 좋은 방법은 각 개별 구성 요소를 고려하여 해당 구성 요소가 완전히 손상되고 악의적 인 행위자가 제어하는 ​​가설 시나리오를 평가하는 것입니다. 응용 프로그램의 각 구성 요소를 차례로 가져 와서 해당 구성 요소가 손상된 경우 전체 보안에 미치는 영향을 평가하십시오. 구성 요소가 손상되었을 때 응용 프로그램이 더 이상 안전하지 않으면 해당 구성 요소에 대한 신뢰가 잘못되었다는 것을 나타냅니다. 취약점이없는 비트 코인 응용 프로그램은 비트 코인 합의 메커니즘의 손상에 취약해야합니다. 즉, 루트의 신뢰는 비트 코닉 보안 아키텍처의 가장 강력한 부분을 기반으로합니다. 응용 프로그램의 보안 아키텍처를 평가하는 좋은 방법은 각 개별 구성 요소를 고려하여 해당 구성 요소가 완전히 손상되고 악의적 인 행위자가 제어하는 ​​가설 시나리오를 평가하는 것입니다. 응용 프로그램의 각 구성 요소를 차례로 가져 와서 해당 구성 요소가 손상된 경우 전체 보안에 미치는 영향을 평가하십시오. 구성 요소가 손상되었을 때 응용 프로그램이 더 이상 안전하지 않으면 해당 구성 요소에 대한 신뢰가 잘못되었다는 것을 나타냅니다. 취약점이없는 비트 코인 응용 프로그램은 비트 코인 합의 메커니즘의 손상에 취약해야합니다. 즉, 루트의 신뢰는 비트 코닉 보안 아키텍처의 가장 강력한 부분을 기반으로합니다.

해킹 된 비트 코인 교환의 수많은 사례는 보안 아키텍처와 디자인이 가장 일상적인 조사에서도 실패하기 때문에이 지점을 강조합니다. 이러한 중앙 집중식 구현은 핫 지갑, 중앙 집중식 원장 데이터베이스, 취약한 암호화 키 및 유사한 구성표와 같이 비트 코 블록 (bitcoin blockchain) 외부의 많은 구성 요소에 명시 적으로 신뢰를 쏟아 붓습니다.((("", startref="Sprinc11")))


=== 사용자 보안 모범 사례

((("security", "user security best practices", id="Suser11")))((("use cases", "user security best practices", id="UCsecurity11")))인간은 물리적 보안을 사용했습니다. (( "보안", "사용자 보안 베스트 프랙티스", id = "Suser11" 수천년 동안의 통제. 이에 비해 우리의 디지털 보안 경험은 50 년 미만입니다. 현대의 범용 운영 체제는 안전하지 않으며 디지털 돈을 저장하는 데 특히 적합하지 않습니다. 우리의 컴퓨터는 항상 인터넷 연결을 통해 외부 위협에 지속적으로 노출되어 있습니다. 수백 명의 작성자가 수천 개의 소프트웨어 구성 요소를 실행하며 대개 사용자 파일에 자유롭게 액세스 할 수 있습니다. 컴퓨터에 설치된 수천 개의 악성 소프트웨어 중 하나가 키보드 및 파일을 손상시키고 Wallet 응용 프로그램에 저장된 비트 코인을 훔칠 수 있습니다.

수십 년에 걸친 정보 보안 분야의 연구 및 발전에도 불구하고 디지털 자산은 여전히 ​​적대적인 결정에 취약합니다. 금융 서비스 회사, 정보 기관 및 방위 산업 계약자에서 가장 보 호되고 제한적인 시스템조차도 자주 파기됩니다. Bitcoin은 본질적인 가치를 지닌 디지털 자산을 생성하여 도난 당하거나 즉시 새 소유자에게 전환 될 수 있습니다. 이것은 해커에 대한 대규모 인센티브를 만듭니다. 지금까지 해커는 신용 카드 및 은행 계좌와 같은 신원 정보 또는 계정 토큰을 손상시킨 후에 가치로 전환해야했습니다. 펜싱 및 금융 정보 세탁의 어려움에도 불구하고, 우리는 끊임없이 증가하는 도난을 보았습니다. Bitcoin은 울타리 또는 세탁 할 필요가 없기 때문에이 문제를 확대합니다.

다행스럽게도 비트 코인은 컴퓨터 보안을 향상시키는 인센티브를 제공합니다. 이전에는 컴퓨터가 손상 될 위험이 모호하고 간접적 이었지만 비트 코인은 이러한 위험을 분명하고 분명하게 만듭니다. 컴퓨터에서 비트 코인을 사용하면 향상된 컴퓨터 보안의 필요성에 사용자의 마음을 집중시킬 수 있습니다. 비트 코인 및 기타 디지털 통화가 확산되고 채택이 증가한 결과, 해킹 기술과 보안 솔루션이 모두 증가한 것으로 나타났습니다. 간단히 말하면, 해커는 이제 매우 수분이 많은 목표를 가지고 있으며 사용자는 자신을 변호 할 분명한 인센티브를 갖고 있습니다.

지난 3 년 동안 비트 코 채택의 직접적인 결과로 하드웨어 암호화, 키 저장 및 하드웨어 지갑, 다중 서명 기술 및 디지털 에스크로 형태로 정보 보안 영역에서 엄청난 혁신을 보았습니다. 다음 섹션에서는 실용적인 사용자 보안을위한 다양한 모범 사례를 살펴 봅니다.

==== 물리적 Bitcoin 저장소

((("storage", "physical bitcoin storage")))((("paper wallets")))((("wallets", "types of", "paper wallets")))((("paper wallets", see="also wallets")))대부분의 사용자는 정보 보안보다 물리적 보안에 훨씬 더 익숙하기 때문에 비트 코인을 보호하는 매우 효과적인 방법은이를 물리적 형태로 변환하는 것입니다. Bitcoin 키는 긴 숫자 이상입니다. 즉, 용지에 인쇄하거나 금속 동전에 새겨 넣은 것과 같은 물리적 인 형태로 저장할 수 있습니다. 키를 안전하게 유지하는 것은 비트 동전 키의 인쇄 된 사본을 물리적으로 안전하게 유지하는 것처럼 간단 해집니다. 종이에 인쇄 된 비트 동전 키 집합을 "종이 지갑"이라고하며,이를 만드는 데 사용할 수있는 많은 무료 도구가 있습니다. 개인적으로 BIP-38로 암호화 된 종이 지갑에 보관 된 대다수의 비트 코인 (99 % 이상)을 금고에 고정 된 상태로 보관합니다. (( "저온 저장"))) (( "저장", "저온 저장"))) 비트 코인을 오프라인으로 유지하는 것을 _cold storage_라고하며 가장 효과적인 보안 기술 중 하나입니다. 콜드 스토리지 시스템은 키가 오프라인 시스템 (인터넷에 연결되지 않은 시스템)에서 생성되어 USB 메모리 스틱과 같이 종이 또는 디지털 미디어에 오프라인으로 저장되는 시스템입니다.

==== 하드웨어 지갑

((("wallets", "types of", "hardware wallets")))((("hardware wallets")))비트 코인 보안은 장기적으로 하드웨어 변조 방지 지갑의 형태를 취할 것입니다. (( "("지갑 ","유형 ","하드웨어 지갑 ")) 스마트 폰이나 데스크탑 컴퓨터와 달리 비트 코인 하드웨어 지갑에는 비트 코인을 안전하게 보관하는 목적이 있습니다. 일반적인 목적의 소프트웨어가 손상되거나 인터페이스가 제한적이더라도 하드웨어 지갑은 일반 사용자에게는 거의 절대 안전한 수준의 보안을 제공 할 수 있습니다. 하드웨어 지갑이 비트 코인 저장 방식의 주류가 될 것으로 예상됩니다. 이러한 하드웨어 지갑의 예는 https://trezor.io/[Trezor]를 참조하십시오.

==== 위험 관리

((("risk, balancing and diversifying", seealso="security")))대부분의 사용자는 비트 코인 절도에 대해 올바르게 염려하지만 더 큰 위험이 있습니다. 데이터 파일은 항상 손실됩니다. 그들이 비트 코인을 포함한다면, 손실은 훨씬 더 고통 스럽습니다. 비트 코인 지갑을 보호하기 위해 사용자는 너무 멀리 가서 비트 코인을 잃지 않도록 조심해야합니다. 2011 년 7 월에 잘 알려진 비트 코인 인식 및 교육 프로젝트로 약 7,000 비트 동전이 손실되었습니다. 도난을 방지하기 위해 소유자는 복잡한 일련의 암호화 된 백업을 구현했습니다. 결국 그들은 우발적으로 암호화 키를 잃어 백업을 무용지물로 만들고 재산을 잃었습니다. 사막에 매장하여 돈을 숨기는 것처럼 비트 코인을 너무 잘 확보하면 다시 찾을 수 없을 수도 있습니다.

==== 위험 분산

지갑에서 전체 순수 가치를 현금으로 소지하고 계십니까? 대부분의 사람들은 무모하다고 생각하지만, 비트 코인 사용자는 흔히 비트 코인을 한 장의 지갑에 보관합니다. 대신 사용자는 여러 비트 코인 지갑간에 위험을 분산시켜야합니다. 신중한 사용자는 온라인 또는 모바일 지갑에 비트 코인을 5 % 미만으로 "포켓 변경"으로 유지합니다. 나머지는 데스크탑 지갑 및 오프라인 (콜드 스토리지)과 같은 몇 가지 다른 저장 메커니즘간에 분할되어야합니다.

==== 다차원 및 지배 구조

((("multisig addresses")))((("addresses", "multisig addresses")))회사 나 개인이 대량의 비트 코를 저장할 때마다 멀티 서명 비트 코인 주소를 사용해야합니다. 다중 서명 주소는 하나 이상의 서명을 요구함으로써 지불을 보증합니다. 서명 키는 여러 다른 위치에 저장해야하며 다른 사람이 제어 할 수 있어야합니다. 예를 들어, 회사 환경에서는 키를 독립적으로 생성하고 여러 회사 임원이 보유하여 독점적 인 사람이 자금을 위험에 빠뜨릴 수 없도록해야합니다. 다중 서명 주소는 또한 한 사람이 여러 위치에 저장된 여러 키를 보유하는 중복을 제공 할 수 있습니다.

==== 생존 가능성

((("survivability")))((("digital asset executors")))((("passwords", "survivability and")))((("security", "passwords")))하나의 중요한 보안 성 (( "생존 가능성")))) 종종 간과되는 고려 사항은 가용성, 특히 키 보유자의 무능력 또는 사망과 관련하여 가용성입니다. Bitcoin 사용자는 복잡한 암호를 사용하고 키를 안전하고 비공개로 유지하며 다른 사람과 공유하지 말라고합니다. 불행하게도 사용자가 잠금을 해제 할 수없는 경우 사용자 가족이 자금을 회수하는 것은 거의 불가능합니다. 대부분의 경우, 비트 코인 사용자의 가족은 비트 코 펀드의 존재를 전혀 모르고있을 수 있습니다.

Bitcoin을 많이 사용하는 경우 신뢰할 수있는 친척이나 변호사와 액세스 세부 정보를 공유하는 것이 좋습니다. 보다 복잡한 생존 성 계획은 "디지털 자산 집행자"로 특화된 변호사를 통해 다중 서명 접근 및 부동산 계획을 수립 할 수 있습니다. ((("", startref="Suser11")))((("", startref="UCsecurity11")))

=== 결론

Bitcoin은 완전히 새로운 전례없는 복잡한 기술입니다. 시간이 지남에 따라 우리는보다 나은 보안 도구와 관행을 개발하여 비관 용자가 사용하기 쉽게 만듭니다. 지금 비트 코인 사용자는 여기에서 설명하는 많은 팁을 사용하여 안전하고 문제없는 비트 코인 경험을 즐길 수 있습니다.
