[머리말]
== 머리말

=== Bitcoin 서적 쓰기

((("bitcoin", "benefits of", id="BCbasicbenefits0")))((("decentralized systems", "bitcoin as")))나는 2011 년 중반에 비트 코인을 처음 발견했습니다. 나의 즉각적인 반응은 어느 정도 "Pfft! Nerd money!"였습니다. 나는 그 중요성을 이해하지 못하고 또 다른 6 개월 동안 그것을 무시했습니다. 이것은 제가 아는 많은 사람들 중에서 제가 반복적으로 보았던 반응입니다. 두 번째로 메일 링리스트 토론에 나왔을 때, 나는 Satoshi Nakamoto가 작성한 백서를 읽고 신뢰할 수있는 출처를 연구하고 그것이 무엇에 관한 것인지 알아보기로 결정했습니다. (비트 콜인 대 비트 코인 대))) 비트 코인은 단순한 디지털 통화가 아니라 신뢰를 제공하는 네트워크라는 것을 깨달았을 때 나는 여전히 9 페이지를 읽은 순간을 기억합니다. 단순한 통화 그 이상을위한 토대. "이것은 돈이 아니며 분산 된 신뢰 네트워크입니다"라는 깨달음은 제가 발견 할 수있는 비트 코에 대한 모든 정보 스크랩을 삼키기 위해 4 개월 간의 여행을 시작했습니다. 나는 매일 적어도 12 시간 이상을 화면에 붙이고, 읽고, 쓰고, 코딩하고, 최대한 많이 학습하는 데 집착하고 열중했습니다. 나는 푸가의이 상태에서, 비트 코인 작업에 자신을 바치기로 결심 한 일관된 식사 부족으로 20 파운드 이상 가벼워졌습니다.

2 년 후 다양한 비트 코인 관련 서비스 및 제품을 탐색 할 수있는 소규모 벤처 기업을 만든 후 첫 번째 책을 쓸 시간이라고 결정했습니다. Bitcoin은 나를 창의력의 광란으로 몰고 내 생각을 소모시킨 주제였습니다. 그것은 내가 인터넷에서 만난 가장 흥미로운 기술이었습니다. 이제이 놀라운 기술에 대한 열정을 더 많은 사람들과 나누어야 할 때입니다.

=== 대상 독자

((("intended audience")))이 책은 주로 코더를 대상으로합니다. 프로그래밍 언어를 사용할 수있는 경우이 설명서는 암호화 통화의 작동 방식, 사용 방법 및 함께 작동하는 소프트웨어 개발 방법을 알려줍니다. 처음 몇 장은 비 코더 (bitcoin과 cryptocurrencies의 내부 동작을 이해하려고 시도하는 사람들)를위한 비트 코어에 대한 심층적 인 소개로도 적합합니다.

=== 표지에 버그가있는 이유는 무엇입니까?

((("decentralized systems", "in nature"))(잎사귀 개미는 식민지 미생물에서 매우 복잡한 행동을 보이는 종이다. 그러나 개개의 개미는 사회적 상호 작용에 의해 유도 된 일련의 단순한 규칙에 따라 작동한다. 화학 냄새 교환 (페로몬). 위키 피 디아 (Wikipedia) : "인간 옆에, 리프 커터 개미가 지구상에서 가장 크고 복잡한 동물 사회를 형성합니다." 잎이 많은 개미는 실제로 잎을 먹지 않고 식민지의 중심 음식원 인 곰팡이를 기른다. 알 겠어? 이 개미는 경작 중입니다!

개미는 계급 기반 사회를 형성하고 자손을 낳기위한 여왕이 있지만 개미 식민지에는 중앙 권위 나 지도자가 없다. 수백만 명의 회원 집단에 의해 전시 된 고도로 지능적이고 정교한 행동은 소셜 네트워크에서 개인의 상호 작용에서 창발 된 속성입니다.

자연은 분산 된 시스템이 탄력적 일 수 있으며 중앙 권한, 계층 구조 또는 복잡한 부분을 필요로하지 않으면 서 창 발적 복잡성과 믿을 수없는 정교함을 나타낼 수 있음을 보여줍니다.

((("decentralized systems", "benefits of")))Bitcoin은 무수히 많은 재무 프로세스를 지원할 수있는 고도로 정교화 된 분산 된 신뢰 네트워크입니다. 그러나 비트 코인 네트워크의 각 노드는 몇 가지 간단한 수학적 규칙을 따릅니다. 많은 노드 사이의 상호 작용은 복잡한 노드의 고유 한 복잡성이나 신뢰가 아니라 정교한 동작의 출현으로 연결됩니다. 개미 식민지와 마찬가지로 비트 코인 네트워크는 중앙 규칙없이 놀라운 규칙을 수행 할 수있는 간단한 규칙을 따르는 단순한 노드의 탄력적 인 네트워크입니다((("", startref="BCbasicbenefits0")))

=== 이 책에 사용 된 규칙

((("typographical conventions")))이 책에는 다음과 같은 인쇄 협약이 사용됩니다.

_Italic_:: 새로운 용어, URL, 전자 메일 주소, 파일 이름 및 파일 확장명을 나타냅니다.

+Constant width+:: 프로그램 목록뿐만 아니라 변수 또는 함수 이름, 데이터베이스, 데이터 유형, 환경 변수, 명령문 및 키워드와 같은 프로그램 요소를 참조하는 단락 내에서 사용됩니다.

**`Constant width bold`**:: 문자 그대로 사용자가 입력해야하는 명령이나 다른 텍스트를 보여줍니다.

_++Constant width italic++_:: 사용자 제공 값 또는 컨텍스트에 의해 결정된 값으로 대체되어야하는 텍스트를 표시합니다.


[TIP]
====
이 아이콘은 팁 또는 제안을 나타냅니다.
====

[NOTE]
====
이 아이콘은 일반적인 참고 사항입니다.
====

[WARNING]
====
이 아이콘은 경고 또는주의를 나타냅니다.
====

=== 코드 예제

((("code examples, obtaining and using", id="codeuse00")))예제는 Python, C ++ 및 Linux 또는 macOS와 같은 Unix 계열 운영 체제의 명령 줄을 사용하여 설명합니다. 모든 코드 스 니펫은 기본 저장소의 _code_ 하위 디렉토리에있는 https://github.com/aantonop/bitcoinbook[GitHub 저장소]에서 사용할 수 있습니다. 책 코드를 포크로 찍거나, 코드 예제를 시도하거나, GitHub를 통해 수정 사항을 제출하십시오.

모든 코드 스 니펫은 해당 언어에 대한 컴파일러 및 해석기를 최소한으로 설치하여 대부분의 운영 체제에서 복제 할 수 있습니다. 필요한 경우 기본 설치 지침과 해당 지침의 출력에 대한 단계별 예제를 제공합니다.

코드 스 니펫 중 일부와 코드 출력이 인쇄용으로 다시 포맷되었습니다. 이 경우 줄은 백 슬래시 (\) 문자와 줄 바꿈 문자로 구분됩니다. 예제를 옮길 때, 두 문자를 제거하고 행을 다시 결합하면 예제와 같은 결과가 나타납니다.

모든 코드 스 니펫은 가능한 경우 실제 값과 계산을 사용하므로 예제에서 예제로 빌드하고 작성한 코드에서 동일한 결과를보고 동일한 값을 계산할 수 있습니다. 예를 들어 개인 키와 해당 공개 키 및 주소는 모두 실제입니다. 샘플 거래, 블록 및 블록 체인 참조는 모두 실제 비트 코인 블록 체인에 도입되었으며 공공 원장의 일부이므로 모든 비트 코인 시스템에서 검토 할 수 있습니다.

=== 코드 예제 사용하기

이 책은 직업을 완성시키는 데 도움이됩니다. 일반적으로 예제 코드가이 책과 함께 제공되면 프로그램 및 설명서에이 코드를 사용할 수 있습니다. 코드의 상당 부분을 복제하지 않는 한 우리에게 허가를 요청할 필요가 없습니다. 예를 들어,이 책의 여러 청크 코드를 사용하는 프로그램을 작성하는 데는 권한이 필요하지 않습니다. O'Reilly 서적에서 CD-ROM을 판매하거나 배포하려면 허가가 필요합니다. 이 책을 인용하고 예제 코드를 인용하여 질문에 대답하는 것은 허가가 필요하지 않습니다. 이 책의 상당량의 예제 코드를 제품 설명서에 통합하려면 허가가 필요합니다.

((("attribution")))귀속되기를 요청 하나, 요구하지는 않습니다. 저작자 표시에는 일반적으로 제목, 저자, 발행인 및 ISBN이 포함됩니다. 예를 들면 : "_Mastering Bitcoin_ Andreas M. Antonopoulos (O'Reilly). 저작권 2017 Andreas M. Antonopoulos, 978-1-491-95438-6. "

((("open source licenses")))이 책의 일부 버전은 https://creativecommons.org/licenses/by-nc/4.0/[CC-BY-NC]와 같은 오픈 소스 라이선스에 따라 제공됩니다. 이 경우 면허 조건이 적용됩니다.

코드 예제를 공정 사용 또는 위에 명시된 권한 범위를 벗어난 것으로 생각되면 패스:[<a href="mailto:permissions@oreilly.com">permissions@oreilly.com</a>].

=== 이 책의 Bitcoin 주소와 트랜잭션

((("getting started", "warnings and cautions")))((("warnings and cautions", "avoid sending money to addresses appearing in book")))((("keys and addresses", "warnings and cautions")))((("transactions", "warnings and cautions")))((("blockchain applications", "warnings and cautions")))((("QR codes", "warnings and cautions")))이 책에서 사용 된 비트 코인 주소, 트랜잭션, 키, QR 코드 및 블록 체인 데이터는 대부분 실제적입니다. 즉, 블록 체인을 검색하고, 예제로 제공되는 트랜잭션을보고, 자신의 스크립트 나 프로그램 등으로 검색 할 수 있습니다.

그러나 주소를 구성하는 데 사용되는 개인 키는이 설명서에 인쇄되거나 "구운"것입니다. 즉,이 주소 중 하나에 돈을 보내면 영원히 돈을 잃게되거나 책을 읽을 수있는 모든 사람이 여기에 인쇄 된 개인 키를 사용하여 돈을 가져갈 수 있습니다.

[경고]
====
이 책의 주소 중 어느 곳에도 돈을 보내지 마십시오. 귀하의 돈은 다른 독자가 가져 가거나 영원히 잃게됩니다.((("", startref="codeuse00")))
====

=== O'Reilly Safari

[role = "safarienabled"]
[NOTE]
====
pass:[<a href="http://oreilly.com/safari" class="orm:hideurl"><em class="hyperlink">Safari</em></a>] (formerly Safari Books Online) is a membership-based training and reference platform for enterprise, government, educators, and individuals.
====

Members have access to thousands of books, training videos, Learning Paths, interactive tutorials, and curated playlists from over 250 publishers, including O’Reilly Media, Harvard Business Review, Prentice Hall Professional, Addison-Wesley Professional, Microsoft Press, Sams, Que, Peachpit Press, Adobe, Focal Press, Cisco Press, John Wiley & Sons, Syngress, Morgan Kaufmann, IBM Redbooks, Packt, Adobe Press, FT Press, Apress, Manning, New Riders, McGraw-Hill, Jones & Bartlett, and Course Technology, among others.

For more information, please visit pass:[<a href="http://oreilly.com/safari" class="orm:hideurl"><em>http://oreilly.com/safari</em></a>].

=== How to Contact Us

((("comments and questions")))((("contact information")))Please address comments and questions concerning this book to the publisher:

++++
<ul class="simplelist">
  <li>O’Reilly Media, Inc.</li>
  <li>1005 Gravenstein Highway North</li>
  <li>Sebastopol, CA 95472</li>
  <li>800-998-9938 (in the United States or Canada)</li>
  <li>707-829-0515 (international or local)</li>
  <li>707-829-0104 (fax)</li>
</ul>
++++

To comment or ask technical questions about this book, send email to pass:[<a class="email" href="mailto:bookquestions@oreilly.com"><em>bookquestions@oreilly.com</em></a>].

For more information about our books, courses, conferences, and news, see our website at link:$$http://www.oreilly.com$$[].

Find us on Facebook: link:$$http://facebook.com/oreilly$$[]

Follow us on Twitter: link:$$http://twitter.com/oreillymedia$$[]

Watch us on YouTube: link:$$http://www.youtube.com/oreillymedia$$[]

[role="pagebreak-before"]
=== Contacting the Author

You can contact me, Andreas M. Antonopoulos, on my personal site:
link:$$https://antonopoulos.com/$$[]

Information about _Mastering Bitcoin_ as well as the Open Edition and translations are available on:
link:$$https://bitcoinbook.info/$$[]

Follow me on Facebook:
link:$$https://facebook.com/AndreasMAntonopoulos$$[]

Follow me on Twitter:
link:$$https://twitter.com/aantonop$$[]

Follow me on Linkedin:
link:$$https://linkedin.com/company/aantonop$$[]

Many thanks to all my patrons who support my work through monthly donations. You can follow my Patreon page here:
link:$$https://patreon.com/aantonop$$[]

=== Acknowledgments

((("acknowledgments", id="acknowledge0")))이 책은 많은 사람들의 노력과 기여를 나타냅니다. cryptocurrencies와 bitcoin에 관한 확실한 기술 서적을 쓰려고 노력하면서, 친구, 동료, 심지어 완전한 이방인들로부터받은 모든 도움에 감사드립니다.

Bitcoin 기술과 Bitcoin 커뮤니티를 구별하는 것은 불가능하며,이 책은 기술에 관한 책과 마찬가지로 커뮤니티의 많은 제품입니다. 이 책에 대한 저의 작업은 처음부터 끝까지 전체 비트 코인 커뮤니티에 격려 받고, 응원하고, 지원하고, 보상했습니다. 무엇보다이 책은 내가 2 년 동안 훌륭한 공동체의 일원이 될 수있게 해 주었고, 나를이 공동체에 받아 들일 수있을만큼 충분히 감사 할 수는 없다. 회의, 이벤트, 세미나, 모임, 피자 모임, 소규모 개인 모임에서 만난 사람들, 트위터, reddit, bitcointalk에서 저와 대화 한 사람들이 너무 많습니다. org 및 GitHub에서이 책에 영향을 미쳤습니다. 이 책에서 발견 한 모든 생각, 비유, 질문, 대답 및 설명은 어느 시점에서 커뮤니티와의 상호 작용을 통해 영감을 얻거나 테스트를 거쳤거나 개선되었습니다. 귀하의 모든 지원에 감사드립니다. 너 없이는이 책은 안 들었을거야. 나는 영원히 감사한다.

물론 저자가되기위한 여행은 첫 번째 책이 나오기 훨씬 전에 시작됩니다. 제 첫 번째 언어 (그리고 학교 교육)는 그리스어 였으므로 대학 1 학년 때 영어 구술 수업을해야했습니다. 저는 저의 영어 작문 선생님 인 다이아나 코르다 (Diana Kordas)에게 감사드립니다. 그 선생님은 그 해에 자신감과 기술을 키울 수있게 도와주었습니다. 나중에 전문가로서 저는 _Network World_ 잡지에 대한 글쓰기를 통해 데이터 센터 주제에 관한 기술 작문 기술을 개발했습니다. _Network World _에서 칼럼니스트로 처음 저술 한 John Dix와 John Gallant와 저의 편집인 인 Michael Cooney와 저의 동료 인 Johna Till Johnson이 저의 칼럼을 편집하여 출판에 적합하게되어 감사드립니다. 4 년 동안 일주일에 500 단어를 쓰면 저에게 충분한 경험을주었습니다.

O'Reilly에게 책 제안서를 제출할 때 저를지지 해준 사람들에게도 참고서를 제공하고 제안서를 검토해 주셔서 감사드립니다. John Gallant, Gregory Ness, Richard Stiennon, Joel Snyder, Adam B. Levine, Sandra Gittlen, John Dix, Johna Till Johnson, Roger Ver 및 Jon Matonis에게 감사드립니다. 제안의 초기 버전을 검토 한 Richard Kagan과 Tymon Mattoszko와 제안서를 복제 한 Matthew Taylor에게 감사드립니다.

O'Reilly title _DNS와 BIND_의 저자 인 Cricket Liu에게 감사 드리며 O'Reilly에게 저를 소개했습니다. 오라일리 (O'Reilly)의 Michael Loukides와 Allyson MacDonald에게도 감사합니다. 오라일리는 몇 달 동안이 책을 만드는 데 도움을주었습니다. Allyson은 마감 시간을 놓치고 계획된 일정에 생명이 개입되면 딜리버리가 지연 될 때 특히 참을성이있었습니다. 두 번째 판의 경우, Timothy McGovern이 인내심있게 편집 한 Kim Cofer와 많은 새로운 다이어그램을 보여준 Rebecca Panzer에게 감사의 인사를 전합니다.

비트 코인은 풀기 어려운 주제이기 때문에 처음 몇 장의 초안은 가장 힘들었습니다. 비트 코인 기술의 한 가지 실마리를 잡을 때마다 나는 모든 것을 끌어 당겨야했습니다. 나는 주제가 이해하기 쉽도록 고투하고 그러한 빽빽한 기술 주제에 대한 서사를 만드는 데 어려움을 겪었을 때마다 반복적으로 조금씩 낙담했다. 결국 나는 비트 코인 (bitcoin)을 사용하는 사람들의 이야기를 통해 비트 코인의 이야기를하기로 결정했고, 전체 책은 훨씬 쉽게 쓰게되었습니다. 나는 이야기를 풀어주고 작가 블록의 순간을 지나갈 수있게 도와 준 친구이자 스승 인 Richard Kagan에게 감사해야합니다. 나는이 책의 첫 번째와 두 번째 판에서 각 장의 초안을 검토 한 Pamela Morgan에게 감사를 드리며, 어려운 질문을 통해 더 좋게 만들 것을 요청했다. 또한 San Francisco Bitcoin Developers Meetup 그룹의 개발자뿐만 아니라 Taariq Lewis 및 Denise Terry 덕분에 초기 자료를 테스트 할 수있었습니다. Infographic 디자인을 담당 한 Andrew Naugler에게도 감사드립니다.

이 책을 개발하는 동안 GitHub에서 초기 초안을 제공하고 대중의 의견을 초청했습니다. 이에 대해 100 건이 넘는 의견, 제안, 수정 및 기고가 제출되었습니다. 그 공헌은 << github_contrib >>에 내 감사와 함께 명시 적으로 인정됩니다. 무엇보다 내 자원 봉사자 인 GitHub 편집자 Ming T. Nguyen (1 판)과 Will Binns (2 판)는 pull 요청을 큐 레이트, 관리 및 해결하고 보고서를 발행하고 GitHub에서 버그를 수정하기 위해 끊임없이 노력했습니다.

책이 초안되면 몇 차례의 기술 검토를 거쳤습니다. Cricket Liu와 Lorne Lantz의 철저한 검토, 의견 및 지원에 감사드립니다.

여러 비트 코인 개발자가 코드 샘플, 리뷰, 의견 및 격려를 제공했습니다. Amir Taaki와 Eric Voskuil에게 예제 코드 스 니펫 및 많은 훌륭한 의견을 제공합니다. Bitcore 부록에 기고 한 Chris Kleeschulte; Vitalik Buterin과 Richard Kiss는 타원 곡선 수학과 코드 기여에 도움을주었습니다. Gavin Andresen은 정정, 의견 및 격려를 요청합니다. 코멘트, 공헌 및 btcd writeup를위한 Michalis Kargakis; 그리고 두 번째 인쇄본을 개선 한 정오표 제출을위한 Robin Inge. 두 번째 에디션에서, 나는 Bitcoin Core 개발자들로부터 많은 도움을 받았다. Eric Lombrozo는 분리 된 증인, 트랜잭션을 다루는 Luke-Jr, 분리 된 증인 및 다른 장들을 검토 한 Johnson Lau 및 많은 다른 사람들 . 나는 Joseph Poon, Tadge Dryja 및 Olaoluwa Osuntokun에게 Lightning Network에 대해 설명하고, 필자의 글을 검토하고, 내가 붙어있을 때 질문에 대답 한 덕분에 빚을졌습니다.

나는 모든 벽을 감싸고있는 서적들이있는 집에서 나를 일으켰던 나의 어머니, 테레사에게 내 말과 책에 대한 나의 사랑을 빚지고있다. 우리 엄마도 1982 년 자기 소개 기술 공룡 이었음에도 불구하고 저에게 첫 번째 컴퓨터를 사 주셨습니다. 나의 아버지, 80 세의 나이에 처음으로 책을 출간 한 토목 기사 인 Menelaos는 논리적이고 분석적인 사고와 과학과 공학에 대한 사랑을 가르쳐주었습니다.

이 여행을 통해 저를지지 해주신 모든 분들께 감사드립니다.

[[github_contrib]]
==== Early Release Draft (GitHub Contributions)

Many contributors offered comments, corrections, and additions to the early-release draft on GitHub. Thank you all for your contributions to this book.

Following is a list of notable GitHub contributors, including their GitHub ID in parentheses:

* Alex Waters (alexwaters)
* Andrew Donald Kennedy (grkvlt)
* bitcoinctf
* Bryan Gmyrek (physicsdude)
* Casey Flynn (cflynn07)
* Chapman Shoop (belovachap)
* Christie D'Anna (avocadobreath)
* Cody Scott (Siecje)
* coinradar
* Cragin Godley (cgodley)
* dallyshalla
* Diego Viola (diegoviola)
* Dirk Jäckel (biafra23)
* Dimitris Tsapakidis (dimitris-t)
* Dmitry Marakasov (AMDmi3)
* drstrangeM
* Ed Eykholt (edeykholt)
* Ed Leafe (EdLeafe)
* Edward Posnak (edposnak)
* Elias Rodrigues (elias19r)
* Eric Voskuil (evoskuil)
* Eric Winchell (winchell)
* Erik Wahlström (erikwam)
* effectsToCause (vericoin)
* Esteban Ordano (eordano)
* ethers
* fabienhinault
* Frank Höger (francyi)
* Gaurav Rana (bitcoinsSG)
* genjix
* halseth
* Holger Schinzel (schinzelh)
* Ioannis Cherouvim (cherouvim)
* Ish Ot Jr. (ishotjr)
* James Addison (jayaddison)
* Jameson Lopp (jlopp)
* Jason Bisterfeldt (jbisterfeldt)
* Javier Rojas (fjrojasgarcia)
* Jeremy Bokobza (bokobza)
* JerJohn15
* Joe Bauers (joebauers)
* joflynn
* Johnson Lau (jl2012)
* Jonathan Cross (jonathancross)
* Jorgeminator
* Kai Bakker (kaibakker)
* Mai-Hsuan Chia (mhchia)
* Marzig (marzig76)
* Maximilian Reichel (phramz)
* Michalis Kargakis (kargakis)
* Michael C. Ippolito (michaelcippolito)
* Mihail Russu (MihailRussu)
* Minh T. Nguyen (enderminh)
* Nagaraj Hubli (nagarajhubli)
* Nekomata (nekomata-3)
* Robert Furse (Rfurse)
* Richard Kiss (richardkiss)
* Ruben Alexander (hizzvizz)
* Sam Ritchie (sritchie)
* Sergej Kotliar (ziggamon)
* Seiichi Uchida (topecongiro)
* Simon de la Rouviere (simondlr)
* Stephan Oeste (Emzy)
* takaya-imai
* Thiago Arrais (thiagoarrais)
* venzen
* Will Binns (wbnns)
* wintercooled
* wjx
* Wojciech Langiewicz (wlk)
* yurigeorgiev4((("", startref="acknowledge0")))
